---
- hosts: all
  become: yes
  tasks:
    - name: Download required roles
      delegate_to: localhost
      command: ansible-galaxy install -r {{ playbook_dir }}/requirements.yml
      become: no
      changed_when: False
      tags: always
    - block:
      - include_role: name=apt_upgrade
      tags: apt_upgrade
    - block:
      - include_role: name=xfce
      tags: xfce
    - block:
      - include_role: name=git
      tags: git
    - block:
      - include_role: name=baztian.python
      tags: python
    - block:
      - include_role: name=baztian.asdf
      tags: asdf
    - block:
      - include_role: name=baztian.emacs
      tags: emacs
    - block:
      - include_role: name=baztian.keepass
      tags: keepass
    - block:
      - include_role: name=baztian.gocryptfs
      tags: gocryptfs
    - block:
      - include_role: name=docker
      tags: docker
    - block:
      - include_role: name=baztian.java
      tags: java
    - block:
      - include_role: name=baztian.jython
      tags: jython
    - block:
      - include_role: name=baztian.vscode
      tags: vscode
    - block:
      - include_role: name=baztian.jetbrains_toolbox
      tags: jetbrains_toolbox
    - block:
      - include_role: name=baztian.js
      tags: js
    - block:
      - include_role: name=baztian.dev_tools
      tags: dev_tools
    - block:
      - include_role: name=baztian.aws
      tags: aws
    - block:
      - include_role: name=baztian.other_installs
      tags: other_installs
    - block:
      - include_role: name=baztian.calibre
      tags: calibre
    - block:
      - include_role: name=vagrant
      tags: vagrant
    - block:
      - include_role: name=eac
      tags: eac
    - block:
      - include_role: name=baztian.joplin
      tags: joplin
