---
- hosts: all
  become: yes
  roles:
    - role: baztian.apt_upgrade
      tags: apt_upgrade
    - role: baztian.xfce
      tags: xfce
    - role: baztian.git
      tags: git
    - role: baztian.docker
      tags: docker
    - role: baztian.vscode
      tags: vscode
    - role: baztian.jetbrains_toolbox
      tags: jetbrains_toolbox
