---
- hosts: all
  become: yes
  roles:
    - role: baztian.apt_upgrade
      tags: apt_upgrade
    - role: baztian.xfce
      tags: xfce
    - role: baztian.git
      tags: git
    - role: baztian.keepass
      tags: keepass
    - role: baztian.gocryptfs
      tags: gocryptfs
    - role: baztian.docker
      tags: docker
    - role: baztian.java
      tags: java
    - role: baztian.vscode
      tags: vscode
    - role: baztian.jetbrains_toolbox
      tags: jetbrains_toolbox
    - role: baztian.js
      tags: js
    - role: baztian.dev_tools
      tags: dev_tools
    - role: baztian.other_apt_installs
      tags: other_apt_installs
