- src: baztian.asdf
- src: baztian.vscode
- src: baztian.pip_venv
- src: baztian.dev_tools
- src: baztian.java
- src: baztian.keepass
- src: baztian.calibre
- src: baztian.joplin
- src: baztian.gocryptfs
- src: baztian.emacs
- src: baztian.jetbrains_toolbox
- src: baztian.js
