- src: baztian.apt_upgrade
- src: baztian.git
- src: baztian.asdf
- src: baztian.vscode
- src: baztian.python
- src: baztian.pip_venv
- src: baztian.dev_tools
- src: baztian.java
- src: baztian.aws
- src: baztian.keepass
- src: baztian.calibre
- src: baztian.joplin
- src: baztian.gocryptfs
- src: baztian.emacs
- src: baztian.jetbrains_toolbox
- src: baztian.js
- src: baztian.jython
- src: baztian.other_installs
- src: baztian.skype
- src: baztian.xfce
