#!/bin/sh
if [ ! -d $HOME/.config/exact-audio-copy/ ]
then
    mkdir -p $HOME/.config/exact-audio-copy/
fi
if [ ! -f $HOME/.config/exact-audio-copy/user.reg ]
then
    docker run -it --rm --entrypoint /bin/sh baztian/wine-eac -c 'cat /wine/userdata/user.reg' > $HOME/.config/exact-audio-copy/user.reg
fi
DATA_DIR=$HOME/Music
if [ -f $HOME/.config/exact-audio-copy/config ]
then
    . $HOME/.config/exact-audio-copy/config
else
    cat << HERE > $HOME/.config/exact-audio-copy/config
DATA_DIR=\$HOME/Music
HERE
fi
if [ ! -d "${DATA_DIR}/" ]
then
    echo Data dir "$DATA_DIR" not a directory. > /dev/stderr
fi
docker run -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -v $HOME/.config/exact-audio-copy/:/wine/userdata/ -v $DATA_DIR:/Data --rm --privileged --cap-drop ALL --device /dev/sg0 --device /dev/sg1 -v /tmp/.X11-unix/:/tmp/.X11-unix/ -e DISPLAY=${DISPLAY} --name wine-eac baztian/wine-eac
