---
- name: Install various dev packages
  apt:
    pkg: "{{ various_dev_apt_packages }}"
  tags: various_dev_apt_packages
- name: Check if already installed
  stat:
    path: /opt/Postman{{ postman_version }}
  register: postman_directory
  tags: postman
- name: Install packages required by Postman App
  # https://learning.getpostman.com/docs/postman/launching_postman/installation_and_updates/#linux-installation
  apt:
    pkg:
      - libgconf-2-4
  tags: postman
- name: Download Postman App
  get_url:
    url: https://dl.pstmn.io/download/version/{{ postman_version }}/linux64
    checksum: "sha1:{{ postman_sha1 }}"
    dest: /tmp/postman{{ postman_version }}.tar.gz
  when: not postman_directory.stat.exists
  tags: postman
- name: Create Postman app directory
  file:
    path: /opt/Postman{{ postman_version }}
    state: directory
  tags: postman
- name: Unarchive Postman App
  unarchive:
    src: /tmp/postman{{ postman_version }}.tar.gz
    extra_opts:
      - "--strip-components=1"
    dest: /opt/Postman{{ postman_version }}
    remote_src: yes
  when: not postman_directory.stat.exists
  tags: postman
- name: Symlink default Postman version
  file:
    src: "/opt/Postman{{ postman_version }}"
    dest: "/opt/Postman"
    state: link
  tags: postman
- name: Create launcher directory
  file:
    path: /usr/local/share/applications
    state: directory
  tags: postman
- name: Copy Postman App desktop launcher
  template:
    src: templates/postman.desktop.j2
    dest: /usr/local/share/applications/postman.desktop
  tags: postman
