---
- name: Install various packages
  apt:
    pkg: "{{ various_apt_packages }}"
- name: Install zoom.us
  # https://support.zoom.us/hc/en-us/articles/205759689-New-Updates-for-Linux
  apt:
    deb: "{{ zoom_deb_url }}"
  tags: zoom_us
- name: Gather installed packages
  package_facts:
  tags: ms_teams
- name: Download Microsoft Teams client
  get_url:
    url: "https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v{{ ms_teams_version }}/teams-for-linux_{{ ms_teams_version }}_amd64.deb"
    checksum: "sha1:{{ ms_teams_sha1 }}"
    dest: "/tmp/teams-for-linux_{{ ms_teams_version }}_amd64.deb"
  tags: ms_teams
  when: ansible_facts.packages['teams-for-linux']|default('undefined') != ms_teams_version
- name: Install Microsoft Teams client
  apt:
    deb: "/tmp/teams-for-linux_{{ ms_teams_version }}_amd64.deb"
  tags: ms_teams
  when: ansible_facts.packages['teams-for-linux']|default('undefined') != ms_teams_version
- name: Add Spotify signing key on remote server to keyring
  apt_key:
    data: "{{ lookup('file', 'spotify.gpg') }}"
    id: 2EBF997C15BDA244B6EBF5D84773BD5E130D1D45
    state: present
  tags: spotify
- name: Add apt repo for Spotify
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    state: present
  tags: spotify
- name: Install Spotify package
  apt:
    pkg: spotify-client
  tags: spotify
