---
- name: Install various packages
  apt:
    pkg: "{{ various_apt_packages }}"
- name: Install zoom.us
  # https://support.zoom.us/hc/en-us/articles/205759689-New-Updates-for-Linux
  apt:
    deb: "{{ zoom_deb_url }}"
  tags: zoom_us
- name: Add Microsoft apt signing key on remote server to keyring
  apt_key:
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    keyserver: keyserver.ubuntu.com
  tags: ms_teams
- name: Add apt repo for ms teams
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main
    # setting filename required to not collide with the one provided by the deb similar to
    # https://github.com/microsoft/vscode/blob/master/resources/linux/debian/postinst.template
    filename: teams
    state: present
  tags: ms_teams
- name: Install Microsoft Teams client
  apt:
    pkg: teams
  tags: ms_teams
- name: Add Microsoft Skype apt signing key on remote server to keyring
  apt_key:
    id: D4040146BE3972509FD57FC71F3045A5DF7587C3
    keyserver: keyserver.ubuntu.com
  tags: skype
- name: Gather installed packages
  package_facts:
  tags: teams_for_linux
- name: Download unofficial Microsoft Teams for Linux client
  get_url:
    url: "https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v{{
       teams_for_linux_version }}/teams-for-linux_{{ teams_for_linux_version }}_amd64.deb"
    checksum: "sha1:{{ teams_for_linux_sha1 }}"
    dest: "/tmp/teams-for-linux_{{ teams_for_linux_version }}_amd64.deb"
  when: ansible_facts.packages['teams-for-linux']|default('undefined') != teams_for_linux_version
  tags: teams_for_linux
- name: Install unofficial Microsoft Teams for Linux client
  apt:
    deb: "/tmp/teams-for-linux_{{ teams_for_linux_version }}_amd64.deb"
  tags: teams_for_linux
  when: ansible_facts.packages['teams-for-linux']|default('undefined') != teams_for_linux_version
- name: Add apt repo for Skype
  apt_repository:
    repo: deb [arch=amd64] https://repo.skype.com/deb stable main
    # setting filename required to not collide with the one provided by the deb similar to
    # https://github.com/microsoft/vscode/blob/master/resources/linux/debian/postinst.template
    filename: skype-stable
    state: present
  tags: skype
- name: Install Skype client
  apt:
    pkg: skypeforlinux
  tags: skype
- name: Add Signal apt signing key on remote server to keyring
  apt_key:
    id: DBA36B5181D0C816F630E889D980A17457F6FB06
    keyserver: keyserver.ubuntu.com
  tags: signal
- name: Add apt repo for Signal
  apt_repository:
    repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
    # setting filename required to not collide with the one provided by the deb similar to
    # https://github.com/microsoft/vscode/blob/master/resources/linux/debian/postinst.template
    filename: signal-xenial
    state: present
  tags: signal
- name: Install Signal client
  apt:
    pkg: signal-desktop
  tags: signal
- name: Add Spotify signing key on remote server to keyring
  apt_key:
    data: "{{ lookup('file', 'spotify.gpg') }}"
    id: 2EBF997C15BDA244B6EBF5D84773BD5E130D1D45
    state: present
  tags: spotify
- name: Add apt repo for Spotify
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    state: present
  tags: spotify
- name: Install Spotify package
  apt:
    pkg: spotify-client
  tags: spotify
