---
- name: Install git and associated packages
  apt:
    pkg:
      - git
      - git-doc
      - gitk
      - meld
- name: Set up git configuration
  git_config:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
  with_dict:
    "{{ git_config }}"
  become: no
- name: Clone bash-git-prompt
  git:
    repo: https://github.com/magicmonty/bash-git-prompt.git
    dest: /opt/bash-git-prompt
    version: "{{ bash_git_prompt_version }}"
- name: Add bash-git-prompt config to .bashrc
  blockinfile:
    path: ~/.bashrc
    block: |
      if [ -f "/opt/bash-git-prompt/gitprompt.sh" ]; then
        GIT_PROMPT_ONLY_IN_REPO=1
        GIT_PROMPT_THEME="Single_line_Dark"
        function prompt_callback {
            gp_set_window_title "\u@\h: $(gp_truncate_pwd)"
        }
        source /opt/bash-git-prompt/gitprompt.sh
      fi
  become: no
