---
- name: Install git and associated packages
  apt:
    pkg:
      - git
      - git-doc
      - gitk
      - meld
- name: Set up git configuration
  git_config:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
  with_dict:
    "{{ git_config }}"
  become: no
- name: Clone bash-git-prompt
  git:
    repo: https://github.com/magicmonty/bash-git-prompt.git
    dest: /opt/bash-git-prompt
    depth: 1
    version: "{{ bash_git_prompt_version }}"
- name: Add bash-git-prompt config
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK bash-git-prompt"
    block: |
      if [ -f "/opt/bash-git-prompt/gitprompt.sh" ]; then
        GIT_PROMPT_ONLY_IN_REPO=1
        GIT_PROMPT_THEME="Single_line_Dark"
        function prompt_callback {
            gp_set_window_title "\u@\h: $(gp_truncate_pwd)"
        }
        source /opt/bash-git-prompt/gitprompt.sh
      fi
  become: no
- name: Install hub
  unarchive:
    src: "https://github.com/github/hub/releases/download/v{{ hub_version }}/hub-linux-amd64-{{ hub_version }}.tgz"
    dest: /opt
    remote_src: yes
- name: Symlink default hub
  file:
    src: "hub-linux-amd64-{{ hub_version }}"
    dest: "/opt/hub"
    state: link
- name: Symlink hub bin
  file:
    src: "/opt/hub/bin/hub"
    dest: "/usr/local/bin/hub"
    state: link
- name: Add hub git alias and setup bash completion
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK git hub"
    block: |
      eval "$(hub alias -s)"
      if [ -f /opt/hub/etc/hub.bash_completion.sh ]; then
        . /opt/hub/etc/hub.bash_completion.sh
      fi
  become: no
- name: Install get_repos.sh
  get_url:
    url: '{{ get_repos_url }}'
    dest: /usr/local/bin/get_repos.sh
    mode: "755"
    force: yes
