---
- name: Install git and associated packages
  apt:
    pkg:
      - git
      - git-doc
      - gitk
      - meld
- name: Set up git configuration
  git_config:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
  with_dict:
    "{{ git_config }}"
  become: no
- name: Clone bash-git-prompt
  git:
    repo: https://github.com/magicmonty/bash-git-prompt.git
    dest: /opt/bash-git-prompt
    version: 9733b12b3441424ad47d4f42977578e8c9d89438
- name: Add bash-git-prompt config to .bashrc
  blockinfile:
    path: ~/.bashrc
    block: |
      if [ -f "/opt/bash-git-prompt/gitprompt.sh" ]; then
        GIT_PROMPT_ONLY_IN_REPO=1
        source /opt/bash-git-prompt/gitprompt.sh
      fi
  become: no
