---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600
- name: Install Vagrant and dependencies
  apt:
    name:
    - vagrant
    - virtualbox
    - virtualbox-guest-additions-iso
    install_recommends: yes
- name: Allow running virtualbox without sudo
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    groups: vboxusers
    append: yes
