---
- name: Add Apt signing key on remote server to keyring
  apt_key:
    data: "{{ lookup('file', 'microsoft.asc') }}"
    state: present
- name: Update repos and upgrade all packages
  apt:
    update_cache: yes
- apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
- name: Install visual studio code package
  apt:
    pkg:
      - code
