---
- name: Add Apt signing key on remote server to keyring
  apt_key:
    data: "{{ lookup('file', 'julianTaylorPPA.gpg') }}"
    id: 57A0E8DEA026F8D8173E90A57858088158B80F90
    # setting keyring required to not collide with
    state: present
- name: Extract distribution base name (works on linux mint as well)
  command: grep -oP 'UBUNTU_CODENAME=\K.*' /etc/os-release
  register: distro
  changed_when: False
- name: Add apt repo for keepass
  apt_repository:
    repo: deb http://ppa.launchpad.net/jtaylor/keepass/ubuntu {{ distro.stdout }} main
    state: present
- name: Add apt repo for keepass sources
  apt_repository:
    repo: deb-src http://ppa.launchpad.net/jtaylor/keepass/ubuntu {{ distro.stdout }} main
    state: present
- name: Install keepass packages
  apt:
    pkg:
      - keepass2
