---
- name: Extract distribution base name (works on linux mint as well)
  command: grep -oP 'UBUNTU_CODENAME=\K.*' /etc/os-release
  register: distro
  changed_when: False
- name: Add Keepass Apt signing key on remote server to keyring
  apt_key:
    data: "{{ lookup('file', 'julianTaylorPPA.gpg') }}"
    id: 57A0E8DEA026F8D8173E90A57858088158B80F90
    state: present
- name: Add apt repo for Keepass 2
  apt_repository:
    repo: "{{ item  }} http://ppa.launchpad.net/jtaylor/keepass/ubuntu {{ distro.stdout }} main"
    state: present
  with_items:
    - deb
    - deb-src
- name: Add KeepassKeeFox Plugin Apt signing key on remote server to keyring
  apt_key:
    data: "{{ lookup('file', 'davidLechnerPPA.gpg') }}"
    id: A8BD96F8FD24E96B60232807B3B4C3CECC10C662
    state: present
- name: Add apt repo for KeeFox Plugin
  apt_repository:
    repo: "{{ item  }} http://ppa.launchpad.net/dlech/keepass2-plugins/ubuntu {{ distro.stdout }} main"
    state: present
  with_items:
    - deb
    - deb-src
- name: Install keepass packages
  apt:
    pkg:
      - keepass2
      - xsel
      - xdotool
      # For firefox integration
      - keepass2-plugin-rpc
      # For (manual) gnome keyring integration
      - libsecret-tools
- name: Check if KPScript already installed
  stat:
    path: /usr/lib/keepass2/KPScript.exe
  register: kpscript_bin
- name: Download KPScript
  get_url:
    url: http://keepass.info/extensions/v2/kpscript/KPScript-{{ kpscript_version }}.zip
    checksum: "sha256:{{ kpscript_sha256 }}"
    dest: /tmp/
  when: not kpscript_bin.stat.exists
- name: Unarchive KPScript
  unarchive:
    src: /tmp/KPScript-{{ kpscript_version }}.zip
    dest: /tmp
    remote_src: yes
  when: not kpscript_bin.stat.exists
- name: Install KPScript binary
  command: install -D -m644 /tmp/KPScript.exe "/usr/lib/keepass2/KPScript.exe"
  when: not kpscript_bin.stat.exists
- name: Install kpscript helper script
  copy:
    src: kpscript
    dest: /usr/local/bin/kpscript
    mode: "755"
