---
- fail:
    msg: Failed installing python package {{ pkg }}. 'version' attribute required.
  when: not version
- name: Install python venv for python {{ py_version }} to allow for software
        install inside virtual python environments
  apt:
    pkg: python{{ py_version }}-venv
- name: Prepare virtual env for {{ pkg }} python package version {{ version }}
  command: python{{ py_version }} -m venv /opt/{{ pkg }}-{{ version }}
  args:
    creates: /opt/{{ pkg }}-{{ version }}
- name: Install {{ pkg }} python package version {{ version }}
  command: /opt/{{ pkg }}-{{ version }}/bin/pip install {{ pkg }}=={{ version }}
  args:
    creates: /opt/{{ pkg }}-{{ version }}/bin/{{ bin if bin is string else bin[-1] }}
- name: Symlink default version {{ version }} for {{ pkg }} python package
  file:
    src: "{{ pkg }}-{{ version }}"
    dest: "/opt/{{ pkg }}"
    state: link
- name: Symlink binary from {{ pkg }} python package
  file:
    src: "/opt/{{ pkg }}/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  with_items: "{{ bin }}"
