name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run ansible-lint
      uses: ansible/ansible-lint-action@775c5d
    - name: Execute ansible playbook
      run: |
        ansible-playbook playbook.yml -i local \
          --skip-tags apt_upgrade,xfce
