name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run ansible-lint
      uses: ansible/ansible-lint-action@master
    - name: Prepare ssh
      run: |
        ssh-keygen -N "" -f ~/.ssh/id_rsa
        ssh-copy-id localhost
    - name: Execute ansible playbook
      run: ansible-playbook playbook.yml -i localhost
