name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run ansible-lint
      uses: ansible/ansible-lint-action@master
    - name: Execute ansible playbook
      run: |
        ansible-playbook playbook.yml -i local \
          --extra-vars "official_apt_sources_replacements=[]"
